allprojects {
    repositories {
        google() // Nécessaire pour Firebase et les plugins Google
        mavenCentral() // Nécessaire pour les dépendances Maven
    }
    subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android {
                    if (namespace == null) {
                        namespace project.group
                    }
                }
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

buildscript {
    repositories {
        google() // Assurez-vous que ce dépôt est inclus
        mavenCentral() // Assurez-vous que ce dépôt est inclus
    }
    dependencies {
        // Ajoutez cette ligne pour Firebase
        classpath 'com.android.tools.build:gradle:7.4.2' // Vérifiez que cette version est compatible avec Gradle
        classpath 'com.google.gms:google-services:4.3.15' // Plugin Google Services
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
